name: Build and Deploy

on: 
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    name: Font build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current configuration
      uses: actions/checkout@v3
      with:
        ref: refs/heads/master
    
    - name: Download font and unzip
      run: |
        mkdir font-in
        wget -O font.zip $(cat .font-url)
        unzip -d font-in font.zip
    
    - name: Run nerd font build
      run: |
        chmod +x build.sh
        bash build.sh
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: patched-fonts
        path: font-out

    - name: copy readme
      run: cp README.md font-out/README.md

    - name: Deploy to main
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: main # The branch the action should deploy to.
        folder: font-out # The folder the action should deploy.
        clean: true
        single-commit: false
        git-config-name: 'github-actions[bot]'
        git-config-email: '41898282+github-actions[bot]@users.noreply.github.com'
